export interface Invoice {
    idhoadon: number,
    maVe: number,
    kieuThanhToan: string,
    maGiaoDich: string,
    tinhTrangThanhToan: string,
    ngayThanhToan: Date,
    ngayDatVe: Date,
    tenKh: string,
    sdt: string,
    gmailKh: string,
    phai: string,
    tongGia: number,
    maChuyenBay: number,
    loaiGhe: string,
    soGhe: string,
}